#!/bin/bash
# s2s statusline - Token tracking with chain to user's global statusline
# Generated by /s2s:init
# Version: 3.1.0
#
# Writes context data to .s2s/context-window.json for token tracking.
# Project-local file, no session ID needed (one state per project).
# Reads roundtable state from .s2s/state.json (written by token-tracker).

INPUT=$(cat)

# === S2S Token Tracking ===
# Get project directory from workspace
PROJECT_DIR=$(echo "$INPUT" | jq -r '.workspace.current_dir // "."')

# Ensure .s2s directory exists
S2S_DIR="${PROJECT_DIR}/.s2s"
mkdir -p "$S2S_DIR" 2>/dev/null

# Save context_window data to project-local file
# Note: total_input_tokens is cumulative for session; current_context_tokens is calculated
echo "$INPUT" | jq '{
  session_id: .session_id,
  used_percentage: .context_window.used_percentage,
  remaining_percentage: .context_window.remaining_percentage,
  context_window_size: .context_window.context_window_size,
  current_context_tokens: ((.context_window.context_window_size // 200000) * (.context_window.used_percentage // 0) / 100 | floor),
  total_input_tokens: .context_window.total_input_tokens,
  total_output_tokens: .context_window.total_output_tokens,
  cost_usd: .cost.total_cost_usd,
  transcript_path: .transcript_path,
  updated_at: now | strftime("%Y-%m-%dT%H:%M:%SZ")
}' > "$S2S_DIR/context-window.json" 2>/dev/null

# === Chain to User's Global Statusline ===
# Read the command path from global settings (not hardcoded)
GLOBAL_SETTINGS="$HOME/.claude/settings.json"
GLOBAL_STATUSLINE=""

if [[ -f "$GLOBAL_SETTINGS" ]]; then
    GLOBAL_STATUSLINE=$(jq -r '.statusLine.command // empty' "$GLOBAL_SETTINGS" 2>/dev/null)
fi

if [[ -n "$GLOBAL_STATUSLINE" && -x "$GLOBAL_STATUSLINE" ]]; then
    # User has a global statusline - chain to it for display
    echo "$INPUT" | "$GLOBAL_STATUSLINE"
else
    # Fallback: s2s-enhanced statusline
    MODEL=$(echo "$INPUT" | jq -r '.model.display_name // "Claude"')
    DIR=$(echo "$INPUT" | jq -r '.workspace.current_dir // "."')
    DIR_NAME=$(basename "$DIR")

    # Get token info - calculate current context from size * percentage
    # Note: total_input_tokens is cumulative for session, NOT current context
    CTX_SIZE=$(echo "$INPUT" | jq -r '.context_window.context_window_size // 200000')
    PCT=$(echo "$INPUT" | jq -r '.context_window.used_percentage // 0' | awk '{printf "%.0f", $1}')
    USED_K=$(awk "BEGIN {printf \"%.0f\", $CTX_SIZE * $PCT / 100 / 1000}")
    AVAIL_K=$(awk "BEGIN {printf \"%.0f\", $CTX_SIZE * (100 - $PCT) / 100 / 1000}")

    # Build progress bar: 10 slots, each = 20k tokens (200k total)
    # Using Claude Code symbols: ⛁ (filled), ⛶ (empty)
    FILLED=$(awk "BEGIN {printf \"%.0f\", $USED_K / 20}")
    [[ $FILLED -gt 10 ]] && FILLED=10
    EMPTY=$((10 - FILLED))
    BAR=""
    for ((i=0; i<FILLED; i++)); do BAR+="⛁ "; done
    for ((i=0; i<EMPTY; i++)); do BAR+="⛶ "; done

    # Git branch if available
    BRANCH=""
    if git rev-parse --git-dir > /dev/null 2>&1; then
        BRANCH=$(git branch --show-current 2>/dev/null)
        [[ -n "$BRANCH" ]] && BRANCH=" on \033[33m$BRANCH\033[0m"
    fi

    # Check for active roundtable session from state.json
    STATE_FILE="$S2S_DIR/state.json"
    RT_INFO=""
    if [[ -f "$STATE_FILE" ]]; then
        RT_WORKFLOW=$(jq -r '.active_session.workflow_type // empty' "$STATE_FILE" 2>/dev/null)
        RT_ROUND=$(jq -r '.active_session.round // empty' "$STATE_FILE" 2>/dev/null)
        RT_STRATEGY=$(jq -r '.active_session.strategy // empty' "$STATE_FILE" 2>/dev/null)

        if [[ -n "$RT_WORKFLOW" && -n "$RT_ROUND" ]]; then
            # Short strategy name
            case "$RT_STRATEGY" in
                "consensus-driven") RT_STRAT_SHORT="cons" ;;
                "standard") RT_STRAT_SHORT="std" ;;
                "disney") RT_STRAT_SHORT="disney" ;;
                "debate") RT_STRAT_SHORT="debate" ;;
                "six-hats") RT_STRAT_SHORT="6hats" ;;
                *) RT_STRAT_SHORT="" ;;
            esac

            if [[ -n "$RT_STRAT_SHORT" ]]; then
                RT_INFO=" | \033[35m${RT_WORKFLOW}:${RT_STRAT_SHORT} R${RT_ROUND}\033[0m"
            else
                RT_INFO=" | \033[35m${RT_WORKFLOW} R${RT_ROUND}\033[0m"
            fi
        fi
    fi

    # Color code context percentage
    if [[ $PCT -lt 60 ]]; then
        PCT_COLOR="\033[32m"  # Green
    elif [[ $PCT -lt 80 ]]; then
        PCT_COLOR="\033[33m"  # Yellow
    else
        PCT_COLOR="\033[31m"  # Red
    fi

    # Output: Model in Dir on Branch | RT info | Xk (Y%) ⛁ ⛁ ⛶ ⛶ Zk
    printf "\033[1m%s\033[0m in \033[36m%s\033[0m%b%b | ${PCT_COLOR}%sk (%s%%)\033[0m %b\033[90m%sk\033[0m\n" \
        "$MODEL" "$DIR_NAME" "$BRANCH" "$RT_INFO" "$USED_K" "$PCT" "$BAR" "$AVAIL_K"
fi
